# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Projeto Redes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'Socket.IO-Client-Swift', '~> 8.3.3' # Or latest version
  use_frameworks!

  # Pods for Projeto Redes

end
